// Kiro Cartographer - Documentation Generator

import type {
  AnalyzeCodebaseOutput,
  GeneratedFile,
  ArchitecturePatterns,
  DependencyEdge,
} from '../types.js';
import type { ArtifactGenerator, GenerationConfig } from './base-generator.js';

/** Header inserted at the top of every generated file. */
const GENERATION_HEADER =
  '<!-- Generated by Kiro Cartographer v1.0.0 | Do not edit manually -->';

/** Placeholder for sections without sufficient data. */
const NOT_DETERMINABLE = '*Could not be determined*';

/**
 * Generates the modules section describing each module's responsibilities and dependencies.
 */
function generateModulesSection(patterns: ArchitecturePatterns): string {
  const sections: string[] = [];

  if (patterns.layers && patterns.layers.length > 0) {
    sections.push('## Modules and Responsibilities\n');
    for (const layer of patterns.layers) {
      sections.push(`### ${layer.name}\n`);
      sections.push(
        `**Responsibilities**: ${layer.responsibilities.length > 0 ? layer.responsibilities.join(', ') : NOT_DETERMINABLE}`
      );
      sections.push('');
      sections.push(
        `**Modules**: ${layer.modules.length > 0 ? layer.modules.join(', ') : NOT_DETERMINABLE}`
      );
      sections.push('');
      if (layer.allowedDependencies.length > 0) {
        sections.push(`**Dependencies**: ${layer.allowedDependencies.join(', ')}`);
      } else {
        sections.push(`**Dependencies**: No explicit dependencies defined`);
      }
      sections.push('');
    }
  } else if (patterns.patterns.length > 0) {
    // Derive modules from pattern evidence
    sections.push('## Modules and Responsibilities\n');
    const dominantPattern = patterns.patterns.find((p) => p.isDominant) ?? patterns.patterns[0];
    if (dominantPattern) {
      for (const evidence of dominantPattern.evidence) {
        sections.push(`### ${evidence.role}\n`);
        sections.push(`**Responsibilities**: ${evidence.description}`);
        sections.push('');
        sections.push(
          `**Files**: ${evidence.files.length > 0 ? evidence.files.slice(0, 10).join(', ') : NOT_DETERMINABLE}`
        );
        sections.push('');
      }
    }
  } else {
    sections.push('## Modules and Responsibilities\n');
    sections.push(NOT_DETERMINABLE);
    sections.push('');
  }

  return sections.join('\n');
}

/**
 * Generates the data flows and communication paths section.
 */
function generateDataFlowsSection(
  patterns: ArchitecturePatterns,
  analysis: AnalyzeCodebaseOutput,
): string {
  const sections: string[] = [];
  sections.push('## Data Flows and Communication Paths\n');

  let hasContent = false;

  // From dependency graph
  if (patterns.dependencyGraph.length > 0) {
    hasContent = true;
    sections.push('### Module Communication\n');
    // Group edges by type for clarity
    const byType = new Map<string, DependencyEdge[]>();
    for (const edge of patterns.dependencyGraph) {
      const existing = byType.get(edge.type) ?? [];
      existing.push(edge);
      byType.set(edge.type, existing);
    }

    for (const [type, edges] of byType) {
      sections.push(`**${capitalizeType(type)}**:\n`);
      // Show top edges by weight
      const topEdges = edges.sort((a, b) => b.weight - a.weight).slice(0, 15);
      for (const edge of topEdges) {
        sections.push(`- \`${edge.source}\` → \`${edge.target}\` (${type})`);
      }
      sections.push('');
    }
  }

  // From state management data flows
  if (!analysis.stateManagement.noStateManagementFound && analysis.stateManagement.dataFlows.length > 0) {
    hasContent = true;
    sections.push('### State Data Flows\n');
    for (const flow of analysis.stateManagement.dataFlows) {
      sections.push(`- \`${flow.source}\` → \`${flow.target}\` (mechanism: ${flow.mechanism})`);
    }
    sections.push('');
  }

  // From API communication
  if (!analysis.apis.noApisFound) {
    hasContent = true;
    sections.push('### API Communication\n');
    if (analysis.apis.restEndpoints.length > 0) {
      sections.push(`- **REST**: ${analysis.apis.restEndpoints.length} endpoints (HTTP)`);
    }
    if (analysis.apis.graphql) {
      sections.push(
        `- **GraphQL**: ${analysis.apis.graphql.queries.length} queries, ${analysis.apis.graphql.mutations.length} mutations (HTTP/WebSocket)`
      );
    }
    if (analysis.apis.grpcServices && analysis.apis.grpcServices.length > 0) {
      sections.push(`- **gRPC**: ${analysis.apis.grpcServices.length} services (HTTP/2)`);
    }
    if (analysis.apis.websocketEndpoints && analysis.apis.websocketEndpoints.length > 0) {
      sections.push(`- **WebSocket**: ${analysis.apis.websocketEndpoints.length} endpoints (WS)`);
    }
    sections.push('');
  }

  if (!hasContent) {
    sections.push(NOT_DETERMINABLE);
    sections.push('');
  }

  return sections.join('\n');
}

/**
 * Generates the design decisions section for non-standard approaches.
 */
function generateDesignDecisionsSection(analysis: AnalyzeCodebaseOutput): string {
  const sections: string[] = [];
  sections.push('## Design Decisions\n');

  let hasContent = false;

  // Non-standard patterns (multiple patterns detected, or unusual combinations)
  const patterns = analysis.patterns.patterns;
  if (patterns.length > 1) {
    hasContent = true;
    sections.push('### Architecture Pattern Combination\n');
    sections.push('The project uses multiple architecture patterns at once:\n');
    for (const pattern of patterns) {
      const dominant = pattern.isDominant ? ' **(dominant)**' : '';
      sections.push(`- **${pattern.type}** (confidence: ${pattern.confidence})${dominant}`);
    }
    sections.push('');
  }

  // Non-standard error handling
  if (!analysis.errorHandling.noPatternsFound) {
    const uniqueStrategies = new Set(analysis.errorHandling.patterns.map((p) => p.strategy));
    if (uniqueStrategies.size > 1) {
      hasContent = true;
      sections.push('### Error Handling Strategy\n');
      sections.push('The project uses multiple error handling strategies:\n');
      for (const pattern of analysis.errorHandling.patterns) {
        sections.push(`- **${pattern.type}**: ${pattern.strategy} — ${pattern.description}`);
      }
      sections.push('');
    }
  }

  // External integrations (gRPC, WebSocket, GraphQL alongside REST)
  if (!analysis.apis.noApisFound) {
    const protocols: string[] = [];
    if (analysis.apis.restEndpoints.length > 0) protocols.push('REST');
    if (analysis.apis.graphql) protocols.push('GraphQL');
    if (analysis.apis.grpcServices && analysis.apis.grpcServices.length > 0) protocols.push('gRPC');
    if (analysis.apis.websocketEndpoints && analysis.apis.websocketEndpoints.length > 0) protocols.push('WebSocket');

    if (protocols.length > 1) {
      hasContent = true;
      sections.push('### Multi-Protocol Communication\n');
      sections.push(`The project uses multiple communication protocols: ${protocols.join(', ')}.\n`);
      sections.push('');
    }
  }

  // Non-standard state management
  if (!analysis.stateManagement.noStateManagementFound) {
    const updateTypes = new Set(analysis.stateManagement.updatePatterns.map((p) => p.type));
    if (updateTypes.size > 2) {
      hasContent = true;
      sections.push('### State Update Patterns\n');
      sections.push(
        `The project uses ${updateTypes.size} different state update mechanisms: ${[...updateTypes].join(', ')}.\n`
      );
      sections.push('');
    }
  }

  if (!hasContent) {
    sections.push(NOT_DETERMINABLE);
    sections.push('');
  }

  return sections.join('\n');
}

function capitalizeType(type: string): string {
  return type.charAt(0).toUpperCase() + type.slice(1);
}

/**
 * DocumentationGenerator produces `.kiro/docs/architecture.md` from analysis results.
 * It generates a comprehensive architecture overview document.
 */
export class DocumentationGenerator implements ArtifactGenerator<AnalyzeCodebaseOutput, GeneratedFile[]> {
  readonly name = 'DocumentationGenerator';

  canGenerate(_analysis: AnalyzeCodebaseOutput): boolean {
    // Can always generate — uses "Could not be determined" for missing sections
    return true;
  }

  async generate(input: AnalyzeCodebaseOutput, config: GenerationConfig): Promise<GeneratedFile[]> {
    // Only generate documentation if the artifact type is enabled
    if (!config.artifactTypes.includes('documentation')) {
      return [];
    }

    const sections: string[] = [
      GENERATION_HEADER,
      '',
      `# Architecture Documentation: ${input.summary.projectName}`,
      '',
      `> Generated at: ${input.summary.analyzedAt}`,
      '',
      '## Overview\n',
      `- **Primary language**: ${input.summary.primaryLanguage}`,
      `- **Files**: ${input.summary.totalFiles}`,
      `- **Directories**: ${input.summary.totalDirectories}`,
    ];

    if (input.summary.detectedPatterns.length > 0) {
      sections.push(`- **Detected patterns**: ${input.summary.detectedPatterns.join(', ')}`);
    }
    sections.push('');

    // Modules section
    sections.push(generateModulesSection(input.patterns));

    // Data flows section
    sections.push(generateDataFlowsSection(input.patterns, input));

    // Design decisions section
    sections.push(generateDesignDecisionsSection(input));

    const content = sections.join('\n');

    return [{
      path: '.kiro/docs/architecture.md',
      type: 'documentation',
      content,
      inclusionMode: 'manual',
    }];
  }
}
