// Codebase Explorer Power - Manifest Manager

import { join, dirname, resolve } from 'node:path';
import type { GeneratedManifest, GeneratedFileEntry, GeneratedFile, ArtifactType } from '../types.js';
import { computeHash } from '../utils/hash.js';
import { safeReadFile, safeWriteFile } from '../utils/file-system.js';

/** Header marking for generated files. */
export const GENERATED_HEADER = '<!-- Generated by Kiro Cartographer v1.0.0 | Do not edit manually -->';

/** Relative path to the manifest file from project root. */
const MANIFEST_RELATIVE_PATH = '.kiro/.generated-manifest.json';

/** Current manifest schema version. */
const MANIFEST_VERSION = '1.0.0';

/** Power name used in the manifest. */
const POWER_NAME = 'kiro-cartographer' as const;

/** Power version used in the manifest. */
const POWER_VERSION = '1.0.0';

/**
 * Conflict type when checking existing files.
 * - 'none': No conflict, safe to write.
 * - 'manual-file': File exists but is not in manifest and has no header (manually created).
 * - 'manual-adopted': File was in manifest but header was removed (manually adopted).
 */
export type ConflictType = 'none' | 'manual-file' | 'manual-adopted';

/**
 * Manages the generated manifest file that tracks all files produced by the power.
 * Provides conflict detection to avoid overwriting manually created or adopted files.
 */
export class ManifestManager {
  private manifest: GeneratedManifest;

  constructor() {
    this.manifest = this.createEmptyManifest();
  }

  /**
   * Loads the manifest from `.kiro/.generated-manifest.json` in the given root path.
   * If the file does not exist or is invalid, starts with an empty manifest.
   */
  async loadManifest(rootPath: string): Promise<void> {
    const manifestPath = join(rootPath, MANIFEST_RELATIVE_PATH);
    const result = await safeReadFile(manifestPath);

    if (result.isError) {
      // File doesn't exist or can't be read — start fresh
      this.manifest = this.createEmptyManifest();
      return;
    }

    try {
      const parsed = JSON.parse(result.value) as GeneratedManifest;
      // Basic validation
      if (parsed.version && Array.isArray(parsed.files)) {
        this.manifest = parsed;
      } else {
        this.manifest = this.createEmptyManifest();
      }
    } catch {
      // Invalid JSON — start fresh
      this.manifest = this.createEmptyManifest();
    }
  }

  /**
   * Saves the current manifest to `.kiro/.generated-manifest.json` in the given root path.
   */
  async saveManifest(rootPath: string): Promise<void> {
    const manifestPath = join(rootPath, MANIFEST_RELATIVE_PATH);
    this.manifest.generatedAt = new Date().toISOString();
    const content = JSON.stringify(this.manifest, null, 2);
    await safeWriteFile(manifestPath, content);
  }

  /**
   * Adds a generated file entry to the manifest.
   * If an entry with the same path already exists, it is updated.
   */
  addEntry(file: GeneratedFile): void {
    const now = new Date().toISOString();
    const hash = computeHash(file.content);

    const existingIndex = this.manifest.files.findIndex(e => e.path === file.path);
    const entry: GeneratedFileEntry = {
      path: file.path,
      type: file.type,
      generatedAt: now,
      hash,
      sourceAnalysis: now,
    };

    if (existingIndex >= 0) {
      this.manifest.files[existingIndex] = entry;
    } else {
      this.manifest.files.push(entry);
    }
  }

  /**
   * Checks if a file at the given path is manually created.
   * A file is manually created if it exists on disk, is NOT in the manifest,
   * and does NOT contain the generated header.
   */
  async isManuallyCreated(rootPath: string, filePath: string): Promise<boolean> {
    // Check if it's in the manifest
    if (this.isInManifest(filePath)) {
      return false;
    }

    // Check if the file exists and has no header
    const fullPath = resolve(rootPath, filePath);
    const result = await safeReadFile(fullPath);

    if (result.isError) {
      // File doesn't exist — not manually created
      return false;
    }

    // File exists and is not in manifest — check for header
    return !result.value.startsWith(GENERATED_HEADER);
  }

  /**
   * Checks if a file was in the manifest but the header was removed (manually adopted).
   * A file is manually adopted if it IS in the manifest but no longer contains the generated header.
   */
  async isManuallyAdopted(rootPath: string, filePath: string): Promise<boolean> {
    // Must be in the manifest
    if (!this.isInManifest(filePath)) {
      return false;
    }

    // Check if the file still has the header
    const fullPath = resolve(rootPath, filePath);
    const result = await safeReadFile(fullPath);

    if (result.isError) {
      // File doesn't exist anymore — not adopted
      return false;
    }

    // File is in manifest but header was removed
    return !result.value.startsWith(GENERATED_HEADER);
  }

  /**
   * Resolves the output path for a generated file, applying an optional subdirectory.
   * For example, with basePath `.kiro/steering/coding-standards.md` and
   * outputSubdirectory `generated`, returns `.kiro/steering/generated/coding-standards.md`.
   */
  getOutputPath(basePath: string, outputSubdirectory?: string): string {
    if (!outputSubdirectory) {
      return basePath;
    }

    const dir = dirname(basePath);
    const fileName = basePath.slice(dir.length + 1);
    return join(dir, outputSubdirectory, fileName);
  }

  /**
   * Checks for conflicts with an existing file.
   * Returns the conflict type:
   * - 'none': No conflict, safe to write.
   * - 'manual-file': File exists, not in manifest, no header (don't overwrite).
   * - 'manual-adopted': File in manifest but header removed (don't update).
   */
  async checkConflict(rootPath: string, filePath: string): Promise<ConflictType> {
    if (await this.isManuallyAdopted(rootPath, filePath)) {
      return 'manual-adopted';
    }

    if (await this.isManuallyCreated(rootPath, filePath)) {
      return 'manual-file';
    }

    return 'none';
  }

  /**
   * Returns the current manifest data (for testing/inspection).
   */
  getManifest(): GeneratedManifest {
    return this.manifest;
  }

  /**
   * Checks whether a file path is tracked in the manifest.
   */
  private isInManifest(filePath: string): boolean {
    return this.manifest.files.some(e => e.path === filePath);
  }

  /**
   * Creates a fresh empty manifest.
   */
  private createEmptyManifest(): GeneratedManifest {
    return {
      version: MANIFEST_VERSION,
      generatedAt: new Date().toISOString(),
      powerName: POWER_NAME,
      powerVersion: POWER_VERSION,
      files: [],
    };
  }
}
