// Codebase Explorer Power - Skill Generator

import type {
  AnalyzeCodebaseOutput,
  GeneratedFile,
  DetectedPattern,
  PatternEvidence,
} from '../types.js';
import type { ArtifactGenerator, GenerationConfig } from './base-generator.js';
import { generateSlug } from '../utils/slug.js';

/** Header inserted at the top of every generated file. */
const GENERATION_HEADER =
  '<!-- Generated by Kiro Cartographer v1.0.0 | Do not edit manually -->';

/** Minimum number of occurrences for a pattern to generate a skill. */
const MIN_OCCURRENCES = 3;

/** Maximum number of skills generated per run. */
const MAX_SKILLS = 10;

/** Maximum lines per code context section. */
const MAX_CODE_LINES = 50;

/**
 * Represents a pattern candidate for skill generation.
 */
interface SkillCandidate {
  title: string;
  triggerDescription: string;
  steps: string[];
  exampleOutput: string;
  sourceFiles: string[];
  occurrences: number;
}

/**
 * Extracts skill candidates from detected architecture patterns.
 * A pattern qualifies if it has evidence with enough files (≥ MIN_OCCURRENCES).
 */
function extractSkillCandidates(analysis: AnalyzeCodebaseOutput): SkillCandidate[] {
  const candidates: SkillCandidate[] = [];

  // Extract from architecture patterns
  for (const pattern of analysis.patterns.patterns) {
    for (const evidence of pattern.evidence) {
      if (evidence.files.length >= MIN_OCCURRENCES) {
        candidates.push(createCandidateFromEvidence(pattern, evidence));
      }
    }
  }

  // Extract from API patterns (repeated endpoint structures)
  if (!analysis.apis.noApisFound && analysis.apis.restEndpoints.length >= MIN_OCCURRENCES) {
    candidates.push({
      title: 'Neuen API-Endpunkt anlegen',
      triggerDescription: 'When a new REST API endpoint needs to be created following the existing pattern.',
      steps: [
        'Create a new route handler file in the appropriate directory.',
        'Define the HTTP method, path, request/response types, and authentication requirements.',
        'Register the route in the application router.',
      ],
      exampleOutput: generateApiEndpointExample(analysis),
      sourceFiles: analysis.apis.restEndpoints.slice(0, 5).map(e => e.filePath),
      occurrences: analysis.apis.restEndpoints.length,
    });
  }

  // Extract from data model patterns (repeated entity structures)
  if (!analysis.dataModels.noModelsFound && analysis.dataModels.entities.length >= MIN_OCCURRENCES) {
    candidates.push({
      title: 'Create new entity',
      triggerDescription: 'When a new data entity/model needs to be created following the existing pattern.',
      steps: [
        'Create a new entity file in the models/entities directory.',
        'Define fields with appropriate types and constraints.',
        'Add relationships to other entities if needed.',
      ],
      exampleOutput: generateEntityExample(analysis),
      sourceFiles: analysis.dataModels.entities.slice(0, 5).map(e => e.filePath),
      occurrences: analysis.dataModels.entities.length,
    });
  }

  // Extract from error handling patterns
  if (!analysis.errorHandling.noPatternsFound && analysis.errorHandling.patterns.length >= MIN_OCCURRENCES) {
    const errorFiles = analysis.errorHandling.patterns.flatMap(p => p.files);
    if (errorFiles.length >= MIN_OCCURRENCES) {
      candidates.push({
        title: 'Error-Handler implementieren',
        triggerDescription: 'When error handling needs to be added following the project error handling strategy.',
        steps: [
          'Identify the appropriate error pattern for the context (try-catch, result-type, etc.).',
          'Implement the error handler with the correct strategy (propagation, retry, fallback, logging).',
          'Ensure the error is properly categorized and logged.',
        ],
        exampleOutput: generateErrorHandlingExample(analysis),
        sourceFiles: errorFiles.slice(0, 5),
        occurrences: errorFiles.length,
      });
    }
  }

  // Extract from state management patterns
  if (!analysis.stateManagement.noStateManagementFound && analysis.stateManagement.stores.length >= MIN_OCCURRENCES) {
    candidates.push({
      title: 'Neuen Store anlegen',
      triggerDescription: 'When a new state store/slice needs to be created following the existing state management pattern.',
      steps: [
        `Create a new store file using ${analysis.stateManagement.solution}.`,
        'Define the state shape with initial values.',
        'Implement actions/mutations for state updates.',
      ],
      exampleOutput: generateStoreExample(analysis),
      sourceFiles: analysis.stateManagement.stores.slice(0, 5).map(s => s.filePath),
      occurrences: analysis.stateManagement.stores.length,
    });
  }

  return candidates;
}

function createCandidateFromEvidence(pattern: DetectedPattern, evidence: PatternEvidence): SkillCandidate {
  const title = `${evidence.role} erstellen (${pattern.type})`;
  return {
    title,
    triggerDescription: `When a new ${evidence.role} component needs to be created in the ${pattern.type} architecture.`,
    steps: [
      `Create a new file in the ${evidence.role} directory following the naming convention.`,
      `Implement the ${evidence.role} interface/class with the required methods.`,
      `Register the new ${evidence.role} in the appropriate module/container.`,
    ],
    exampleOutput: `// New ${evidence.role} following the ${pattern.type} pattern\n// See: ${evidence.files[0] ?? 'existing files'}`,
    sourceFiles: evidence.files.slice(0, 5),
    occurrences: evidence.files.length,
  };
}

function generateApiEndpointExample(analysis: AnalyzeCodebaseOutput): string {
  const endpoint = analysis.apis.restEndpoints[0];
  if (!endpoint) return '// New API endpoint';
  return `// ${endpoint.method} ${endpoint.path}\n// File: ${endpoint.filePath}`;
}

function generateEntityExample(analysis: AnalyzeCodebaseOutput): string {
  const entity = analysis.dataModels.entities[0];
  if (!entity) return '// New entity';
  const fields = entity.fields.slice(0, 3).map(f => `  ${f.name}: ${f.dataType}`).join('\n');
  return `// Entity: ${entity.name}\n// Detection: ${entity.detectionMethod}\n${fields}`;
}

function generateErrorHandlingExample(analysis: AnalyzeCodebaseOutput): string {
  const pattern = analysis.errorHandling.patterns[0];
  if (!pattern) return '// Error handling';
  return `// Pattern: ${pattern.type}\n// Strategy: ${pattern.strategy}\n// ${pattern.description}`;
}

function generateStoreExample(analysis: AnalyzeCodebaseOutput): string {
  const store = analysis.stateManagement.stores[0];
  if (!store) return '// New store';
  return `// Store: ${store.name}\n// Solution: ${analysis.stateManagement.solution}\n// Slices: ${store.slices.join(', ')}`;
}

/**
 * Formats a skill candidate into a markdown skill file.
 */
function formatSkill(candidate: SkillCandidate): string {
  const sections: string[] = [
    GENERATION_HEADER,
    '',
    `# ${candidate.title}`,
    '',
    '## Trigger',
    '',
    candidate.triggerDescription,
    '',
    '## Steps',
    '',
  ];

  for (let i = 0; i < candidate.steps.length; i++) {
    sections.push(`${i + 1}. ${candidate.steps[i]}`);
  }

  sections.push('');
  sections.push('## Example Output');
  sections.push('');
  sections.push('```');
  // Limit example output to MAX_CODE_LINES
  const exampleLines = candidate.exampleOutput.split('\n');
  const limitedExample = exampleLines.slice(0, MAX_CODE_LINES).join('\n');
  sections.push(limitedExample);
  sections.push('```');

  // Code Context section with referenced source files
  if (candidate.sourceFiles.length > 0) {
    sections.push('');
    sections.push('## Code Context');
    sections.push('');
    sections.push('Referenced source files:');
    sections.push('');
    for (const file of candidate.sourceFiles.slice(0, 5)) {
      sections.push(`- \`${file}\``);
    }
  }

  return sections.join('\n');
}

/**
 * SkillGenerator produces `.kiro/skills/` files from analysis results.
 * It generates skills for patterns that occur at least 3 times, up to a maximum of 10 skills.
 */
export class SkillGenerator implements ArtifactGenerator<AnalyzeCodebaseOutput, GeneratedFile[]> {
  readonly name = 'SkillGenerator';

  canGenerate(analysis: AnalyzeCodebaseOutput): boolean {
    const candidates = extractSkillCandidates(analysis);
    return candidates.length > 0;
  }

  async generate(input: AnalyzeCodebaseOutput, config: GenerationConfig): Promise<GeneratedFile[]> {
    // Only generate skills if the artifact type is enabled
    if (!config.artifactTypes.includes('skills')) {
      return [];
    }

    const candidates = extractSkillCandidates(input);

    if (candidates.length === 0) {
      return [];
    }

    // Sort by occurrences (most frequent first) and limit to max skills
    const maxSkills = config.userProfile.maxSkillCount ?? MAX_SKILLS;
    const effectiveMax = Math.min(maxSkills, MAX_SKILLS);
    const selectedCandidates = candidates
      .sort((a, b) => b.occurrences - a.occurrences)
      .slice(0, effectiveMax);

    const files: GeneratedFile[] = [];

    for (const candidate of selectedCandidates) {
      const slug = generateSlug(candidate.title);
      const content = formatSkill(candidate);

      files.push({
        path: `.kiro/skills/${slug}.md`,
        type: 'skills',
        content,
        inclusionMode: 'manual',
      });
    }

    return files;
  }
}
