// Codebase Explorer Power - Steering File Generator

import type {
  AnalyzeCodebaseOutput,
  GeneratedFile,
  BuildPipelineAnalysis,
  ArchitecturePatterns,
  TeamConventions,
} from '../types.js';
import type { ArtifactGenerator, GenerationConfig } from './base-generator.js';

/** Header inserted at the top of every generated file. */
const GENERATION_HEADER =
  '<!-- Generated by Kiro Cartographer v1.0.0 | Do not edit manually -->';

/**
 * Determines the inclusion mode based on data quality/confidence.
 * High confidence data (explicit config files, clear patterns) → 'auto'
 * Low confidence data (heuristics, incomplete info) → 'manual'
 */
function determineInclusionMode(confidence: 'high' | 'medium' | 'low'): 'auto' | 'manual' {
  return confidence === 'high' ? 'auto' : 'manual';
}

/**
 * Generates the Coding-Standards steering file content.
 */
function generateCodingStandards(
  teamConventions: TeamConventions,
  analysis: AnalyzeCodebaseOutput,
): { content: string; confidence: 'high' | 'medium' | 'low' } | null {
  const sections: string[] = [];
  let hasData = false;
  let confidence: 'high' | 'medium' | 'low' = 'high';

  // Naming Conventions
  const naming = teamConventions.naming;
  if (naming && (naming.files || naming.variables || naming.classes || naming.constants)) {
    hasData = true;
    sections.push('## Naming Conventions\n');
    if (naming.files) sections.push(`- **Files**: ${naming.files}`);
    if (naming.variables) sections.push(`- **Variables**: ${naming.variables}`);
    if (naming.classes) sections.push(`- **Classes**: ${naming.classes}`);
    if (naming.constants) sections.push(`- **Constants**: ${naming.constants}`);
    sections.push('');
  }

  // Formatting
  const formatting = teamConventions.formatting;
  if (formatting && (formatting.indentation || formatting.maxLineLength || formatting.semicolons !== undefined)) {
    hasData = true;
    sections.push('## Formatting\n');
    if (formatting.indentation) {
      const indent = formatting.indentation === 'spaces'
        ? `${formatting.indentSize ?? 2} spaces`
        : 'tabs';
      sections.push(`- **Indentation**: ${indent}`);
    }
    if (formatting.maxLineLength) sections.push(`- **Max line length**: ${formatting.maxLineLength}`);
    if (formatting.trailingComma !== undefined) sections.push(`- **Trailing comma**: ${formatting.trailingComma ? 'yes' : 'no'}`);
    if (formatting.semicolons !== undefined) sections.push(`- **Semicolons**: ${formatting.semicolons ? 'required' : 'omitted'}`);
    sections.push('');
  }

  // Import Order
  const imports = teamConventions.imports;
  if (imports && imports.order && imports.order.length > 0) {
    hasData = true;
    sections.push('## Import Order\n');
    imports.order.forEach((group, index) => {
      sections.push(`${index + 1}. ${group}`);
    });
    if (imports.groupSeparator) {
      sections.push('\nSeparate groups with a blank line.');
    }
    sections.push('');
  }

  // If no team conventions, try to infer from analysis patterns
  if (!hasData) {
    // Check if we have any detected patterns that hint at conventions
    const patterns = analysis.patterns;
    if (patterns.layers && patterns.layers.length > 0) {
      // We have some structural info but no explicit conventions
      confidence = 'low';
      hasData = true;
      sections.push('## Naming Conventions\n');
      sections.push('- No explicit naming conventions detected. Review and adjust as needed.');
      sections.push('');
      sections.push('## Formatting\n');
      sections.push('- No explicit formatting rules detected. Review and adjust as needed.');
      sections.push('');
      sections.push('## Import Order\n');
      sections.push('- No explicit import order detected. Review and adjust as needed.');
      sections.push('');
    }
  }

  if (!hasData) {
    return null;
  }

  // If conventions come from explicit team config, confidence is high
  // If inferred from analysis, confidence is lower
  if (naming || formatting || imports) {
    confidence = 'high';
  }

  const content = [
    GENERATION_HEADER,
    '',
    `---`,
    `inclusion: ${determineInclusionMode(confidence)}`,
    `---`,
    '',
    '# Coding Standards',
    '',
    ...sections,
  ].join('\n');

  return { content, confidence };
}

/**
 * Generates the Build-and-Test steering file content.
 */
function generateBuildAndTest(
  buildPipeline: BuildPipelineAnalysis,
): { content: string; confidence: 'high' | 'medium' | 'low' } | null {
  if (buildPipeline.noBuildToolFound && buildPipeline.scripts.length === 0) {
    return null;
  }

  const sections: string[] = [];
  let confidence: 'high' | 'medium' | 'low' = 'high';

  // Build Tool
  if (buildPipeline.buildTool) {
    sections.push('## Build Tool\n');
    sections.push(`- **Tool**: ${buildPipeline.buildTool.name}`);
    sections.push(`- **Config**: ${buildPipeline.buildTool.configFile}`);
    if (buildPipeline.buildTool.version) {
      sections.push(`- **Version**: ${buildPipeline.buildTool.version}`);
    }
    sections.push('');
  }

  // Build Commands
  const buildScripts = buildPipeline.scripts.filter(s => s.type === 'build');
  if (buildScripts.length > 0) {
    sections.push('## Build Commands\n');
    for (const script of buildScripts) {
      sections.push(`- \`${script.name}\`: \`${script.command}\``);
    }
    sections.push('');
  }

  // Test Commands
  const testScripts = buildPipeline.scripts.filter(s => s.type === 'test');
  if (testScripts.length > 0) {
    sections.push('## Test Commands\n');
    for (const script of testScripts) {
      sections.push(`- \`${script.name}\`: \`${script.command}\``);
    }
    sections.push('');
  }

  // Lint Commands
  const lintScripts = buildPipeline.scripts.filter(s => s.type === 'lint');
  if (lintScripts.length > 0) {
    sections.push('## Lint Commands\n');
    for (const script of lintScripts) {
      sections.push(`- \`${script.name}\`: \`${script.command}\``);
    }
    sections.push('');
  }

  // Other Commands
  const otherScripts = buildPipeline.scripts.filter(s => s.type === 'other');
  if (otherScripts.length > 0) {
    sections.push('## Other Commands\n');
    for (const script of otherScripts) {
      sections.push(`- \`${script.name}\`: \`${script.command}\``);
    }
    sections.push('');
  }

  if (sections.length === 0) {
    return null;
  }

  // Scripts extracted from config files are high confidence
  confidence = buildPipeline.buildTool ? 'high' : 'medium';

  const content = [
    GENERATION_HEADER,
    '',
    `---`,
    `inclusion: ${determineInclusionMode(confidence)}`,
    `---`,
    '',
    '# Build and Test',
    '',
    ...sections,
  ].join('\n');

  return { content, confidence };
}

/**
 * Generates the Architecture steering file content.
 */
function generateArchitecture(
  patterns: ArchitecturePatterns,
): { content: string; confidence: 'high' | 'medium' | 'low' } | null {
  const hasPatterns = patterns.patterns.length > 0;
  const hasLayers = patterns.layers && patterns.layers.length > 0;
  const hasDependencyGraph = patterns.dependencyGraph.length > 0;

  if (!hasPatterns && !hasLayers && !hasDependencyGraph) {
    return null;
  }

  const sections: string[] = [];
  let confidence: 'high' | 'medium' | 'low' = 'medium';

  // Layers
  if (hasLayers && patterns.layers) {
    sections.push('## Layers\n');
    for (const layer of patterns.layers) {
      sections.push(`### ${layer.name}\n`);
      sections.push(`**Responsibilities**: ${layer.responsibilities.join(', ')}`);
      sections.push(`**Modules**: ${layer.modules.join(', ')}`);
      if (layer.allowedDependencies.length > 0) {
        sections.push(`**Allowed dependencies**: ${layer.allowedDependencies.join(', ')}`);
      }
      sections.push('');
    }
    confidence = 'high';
  }

  // Communication Paths
  if (hasDependencyGraph) {
    sections.push('## Communication Paths\n');
    // Group by source
    const bySource = new Map<string, typeof patterns.dependencyGraph>();
    for (const edge of patterns.dependencyGraph) {
      const existing = bySource.get(edge.source) ?? [];
      existing.push(edge);
      bySource.set(edge.source, existing);
    }
    for (const [source, edges] of bySource) {
      for (const edge of edges) {
        sections.push(`- \`${source}\` → \`${edge.target}\` (${edge.type})`);
      }
    }
    sections.push('');
  }

  // Allowed Dependencies (from layers)
  if (hasLayers && patterns.layers) {
    const hasForbidden = patterns.layers.some(l => l.allowedDependencies.length > 0);
    if (hasForbidden) {
      sections.push('## Dependency Rules\n');
      for (const layer of patterns.layers) {
        if (layer.allowedDependencies.length > 0) {
          sections.push(`- **${layer.name}** may depend on: ${layer.allowedDependencies.join(', ')}`);
        }
      }
      sections.push('');
    }
  }

  if (sections.length === 0) {
    return null;
  }

  const content = [
    GENERATION_HEADER,
    '',
    `---`,
    `inclusion: ${determineInclusionMode(confidence)}`,
    `---`,
    '',
    '# Architecture',
    '',
    ...sections,
  ].join('\n');

  return { content, confidence };
}

/**
 * SteeringFileGenerator produces `.kiro/steering/` files from analysis results.
 * It generates up to three files: coding-standards.md, build-and-test.md, architecture.md.
 */
export class SteeringFileGenerator implements ArtifactGenerator<AnalyzeCodebaseOutput, GeneratedFile[]> {
  readonly name = 'SteeringFileGenerator';

  canGenerate(analysis: AnalyzeCodebaseOutput): boolean {
    // Can generate if we have build pipeline data, architecture patterns, or team conventions
    const hasBuildData = !analysis.buildPipeline.noBuildToolFound || analysis.buildPipeline.scripts.length > 0;
    const hasPatterns = analysis.patterns.patterns.length > 0 ||
      (analysis.patterns.layers !== undefined && analysis.patterns.layers.length > 0) ||
      analysis.patterns.dependencyGraph.length > 0;

    return hasBuildData || hasPatterns;
  }

  async generate(input: AnalyzeCodebaseOutput, config: GenerationConfig): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];

    // Only generate steering files if the artifact type is enabled
    if (!config.artifactTypes.includes('steering')) {
      return files;
    }

    // Coding Standards
    if (
      config.steeringCategories.length === 0 ||
      config.steeringCategories.some(c => ['naming-conventions', 'formatting', 'import-order'].includes(c))
    ) {
      const codingStandards = generateCodingStandards(config.teamConventions, input);
      if (codingStandards) {
        files.push({
          path: '.kiro/steering/coding-standards.md',
          type: 'steering',
          content: codingStandards.content,
          inclusionMode: determineInclusionMode(codingStandards.confidence),
        });
      }
    }

    // Build and Test
    if (
      config.steeringCategories.length === 0 ||
      config.steeringCategories.some(c => ['build-commands', 'test-commands'].includes(c))
    ) {
      const buildAndTest = generateBuildAndTest(input.buildPipeline);
      if (buildAndTest) {
        files.push({
          path: '.kiro/steering/build-and-test.md',
          type: 'steering',
          content: buildAndTest.content,
          inclusionMode: determineInclusionMode(buildAndTest.confidence),
        });
      }
    }

    // Architecture
    if (
      config.steeringCategories.length === 0 ||
      config.steeringCategories.includes('architecture')
    ) {
      const architecture = generateArchitecture(input.patterns);
      if (architecture) {
        files.push({
          path: '.kiro/steering/architecture.md',
          type: 'steering',
          content: architecture.content,
          inclusionMode: determineInclusionMode(architecture.confidence),
        });
      }
    }

    return files;
  }
}
