// Codebase Explorer Power - Steering File Generator

import type {
  AnalyzeCodebaseOutput,
  GeneratedFile,
  BuildPipelineAnalysis,
  ArchitecturePatterns,
  TeamConventions,
  ConventionAnalysis,
} from '../types.js';
import type { ArtifactGenerator, GenerationConfig } from './base-generator.js';

/** Header inserted at the top of every generated file. */
const GENERATION_HEADER =
  '<!-- Generated by Kiro Cartographer v1.0.0 | Do not edit manually -->';

/**
 * Determines the inclusion mode based on data quality/confidence.
 * High confidence data (explicit config files, clear patterns) → 'auto'
 * Low confidence data (heuristics, incomplete info) → 'manual'
 */
function determineInclusionMode(confidence: 'high' | 'medium' | 'low'): 'auto' | 'manual' {
  return confidence === 'high' ? 'auto' : 'manual';
}

/**
 * Generates the Coding-Standards steering file content.
 * Uses detected conventions from source analysis when available,
 * falls back to team conventions config, then to defaults.
 */
function generateCodingStandards(
  teamConventions: TeamConventions,
  analysis: AnalyzeCodebaseOutput,
): { content: string; confidence: 'high' | 'medium' | 'low' } | null {
  const sections: string[] = [];
  const conventions = analysis.conventions;
  let overallConfidence: 'high' | 'medium' | 'low' = 'medium';

  // ─── Naming Conventions ─────────────────────────────────────────────────
  const fileNaming = conventions?.naming.files;
  const naming = teamConventions.naming;

  const filesConvention = fileNaming?.value ?? naming?.files;
  const variablesConvention = naming?.variables ?? 'camelCase';
  const classesConvention = naming?.classes ?? 'PascalCase';
  const constantsConvention = naming?.constants ?? 'UPPER_SNAKE_CASE';

  if (filesConvention) {
    sections.push('## Naming Conventions\n');
    sections.push(`- **Files**: ${filesConvention}`);
    sections.push(`- **Variables**: ${variablesConvention}`);
    sections.push(`- **Classes**: ${classesConvention}`);
    sections.push(`- **Constants**: ${constantsConvention}`);
    sections.push('');

    if (fileNaming && fileNaming.confidence === 'high') {
      overallConfidence = 'high';
    }
  }

  // ─── Formatting ─────────────────────────────────────────────────────────
  const fmt = conventions?.formatting;
  const cfgFmt = teamConventions.formatting;

  const indentType = fmt?.indentation.value ?? cfgFmt?.indentation ?? 'spaces';
  const indentSize = fmt?.indentSize.value ?? cfgFmt?.indentSize ?? 2;
  const semicolons = fmt?.semicolons.value ?? cfgFmt?.semicolons;
  const trailingComma = fmt?.trailingComma.value ?? cfgFmt?.trailingComma;
  const maxLineLength = fmt?.maxLineLength?.value ?? cfgFmt?.maxLineLength;

  sections.push('## Formatting\n');
  const indentLabel = indentType === 'spaces' ? `${indentSize} spaces` : 'tabs';
  sections.push(`- **Indentation**: ${indentLabel}`);
  if (maxLineLength) sections.push(`- **Max line length**: ${maxLineLength}`);
  if (trailingComma !== undefined) sections.push(`- **Trailing comma**: ${trailingComma ? 'yes' : 'no'}`);
  if (semicolons !== undefined) sections.push(`- **Semicolons**: ${semicolons ? 'required' : 'omitted'}`);
  sections.push('');

  if (fmt && (fmt.indentation.source === 'config-file' || fmt.semicolons.source === 'config-file')) {
    overallConfidence = 'high';
  } else if (fmt && fmt.indentation.confidence === 'high') {
    overallConfidence = 'high';
  }

  // ─── Comment Style ──────────────────────────────────────────────────────
  const commentStyle = conventions?.commentStyle;
  if (commentStyle && commentStyle.value !== 'none' && commentStyle.confidence !== 'low') {
    sections.push('## Comment Style\n');
    switch (commentStyle.value) {
      case 'jsdoc':
        sections.push('- **Style**: JSDoc (`/** ... */`) on public functions and methods');
        break;
      case 'inline':
        sections.push('- **Style**: Inline comments (`//`) above functions');
        break;
      case 'minimal':
        sections.push('- **Style**: Minimal — comments only where non-obvious');
        break;
    }
    sections.push('');
  }

  // ─── Import Order ───────────────────────────────────────────────────────
  const importConv = conventions?.imports;
  const cfgImports = teamConventions.imports;

  const importOrder = cfgImports?.order ?? importConv?.order ?? ['builtin', 'external', 'internal', 'relative'];
  const groupSeparator = importConv?.groupSeparator.value ?? cfgImports?.groupSeparator ?? true;

  sections.push('## Import Order\n');
  importOrder.forEach((group, index) => {
    sections.push(`${index + 1}. ${group}`);
  });
  if (groupSeparator) {
    sections.push('\nSeparate groups with a blank line.');
  }
  sections.push('');

  // ─── Source Info ────────────────────────────────────────────────────────
  if (conventions) {
    const sources: string[] = [];
    if (conventions.hasConfigFile) sources.push('config files (.prettierrc, .editorconfig, etc.)');
    if (conventions.sampledFiles > 0) sources.push(`${conventions.sampledFiles} sampled source files`);
    if (sources.length > 0) {
      sections.push(`> Detected from: ${sources.join(' and ')}`);
      sections.push('');
    }
  }

  const content = [
    GENERATION_HEADER,
    '',
    `---`,
    `inclusion: ${determineInclusionMode(overallConfidence)}`,
    `---`,
    '',
    '# Coding Standards',
    '',
    ...sections,
  ].join('\n');

  return { content, confidence: overallConfidence };
}

/**
 * Generates the Build-and-Test steering file content.
 */
function generateBuildAndTest(
  buildPipeline: BuildPipelineAnalysis,
): { content: string; confidence: 'high' | 'medium' | 'low' } | null {
  if (buildPipeline.noBuildToolFound && buildPipeline.scripts.length === 0) {
    return null;
  }

  const sections: string[] = [];
  let confidence: 'high' | 'medium' | 'low' = 'high';

  // Build Tool
  if (buildPipeline.buildTool) {
    sections.push('## Build Tool\n');
    sections.push(`- **Tool**: ${buildPipeline.buildTool.name}`);
    sections.push(`- **Config**: ${buildPipeline.buildTool.configFile}`);
    if (buildPipeline.buildTool.version) {
      sections.push(`- **Version**: ${buildPipeline.buildTool.version}`);
    }
    sections.push('');
  }

  // Build Commands
  const buildScripts = buildPipeline.scripts.filter(s => s.type === 'build');
  if (buildScripts.length > 0) {
    sections.push('## Build Commands\n');
    for (const script of buildScripts) {
      sections.push(`- \`${script.name}\`: \`${script.command}\``);
    }
    sections.push('');
  }

  // Test Commands
  const testScripts = buildPipeline.scripts.filter(s => s.type === 'test');
  if (testScripts.length > 0) {
    sections.push('## Test Commands\n');
    for (const script of testScripts) {
      sections.push(`- \`${script.name}\`: \`${script.command}\``);
    }
    sections.push('');
  }

  // Lint Commands
  const lintScripts = buildPipeline.scripts.filter(s => s.type === 'lint');
  if (lintScripts.length > 0) {
    sections.push('## Lint Commands\n');
    for (const script of lintScripts) {
      sections.push(`- \`${script.name}\`: \`${script.command}\``);
    }
    sections.push('');
  }

  // Other Commands
  const otherScripts = buildPipeline.scripts.filter(s => s.type === 'other');
  if (otherScripts.length > 0) {
    sections.push('## Other Commands\n');
    for (const script of otherScripts) {
      sections.push(`- \`${script.name}\`: \`${script.command}\``);
    }
    sections.push('');
  }

  if (sections.length === 0) {
    return null;
  }

  // Scripts extracted from config files are high confidence
  confidence = buildPipeline.buildTool ? 'high' : 'medium';

  const content = [
    GENERATION_HEADER,
    '',
    `---`,
    `inclusion: ${determineInclusionMode(confidence)}`,
    `---`,
    '',
    '# Build and Test',
    '',
    ...sections,
  ].join('\n');

  return { content, confidence };
}

/**
 * Generates the Architecture steering file content.
 */
function generateArchitecture(
  patterns: ArchitecturePatterns,
): { content: string; confidence: 'high' | 'medium' | 'low' } | null {
  const hasPatterns = patterns.patterns.length > 0;
  const hasLayers = patterns.layers && patterns.layers.length > 0;
  const hasDependencyGraph = patterns.dependencyGraph.length > 0;

  if (!hasPatterns && !hasLayers && !hasDependencyGraph) {
    return null;
  }

  const sections: string[] = [];
  let confidence: 'high' | 'medium' | 'low' = 'medium';

  // Layers
  if (hasLayers && patterns.layers) {
    sections.push('## Layers\n');
    for (const layer of patterns.layers) {
      sections.push(`### ${layer.name}\n`);
      sections.push(`**Responsibilities**: ${layer.responsibilities.join(', ')}`);
      sections.push(`**Modules**: ${layer.modules.join(', ')}`);
      if (layer.allowedDependencies.length > 0) {
        sections.push(`**Allowed dependencies**: ${layer.allowedDependencies.join(', ')}`);
      }
      sections.push('');
    }
    confidence = 'high';
  }

  // Communication Paths
  if (hasDependencyGraph) {
    sections.push('## Communication Paths\n');
    // Group by source
    const bySource = new Map<string, typeof patterns.dependencyGraph>();
    for (const edge of patterns.dependencyGraph) {
      const existing = bySource.get(edge.source) ?? [];
      existing.push(edge);
      bySource.set(edge.source, existing);
    }
    for (const [source, edges] of bySource) {
      for (const edge of edges) {
        sections.push(`- \`${source}\` → \`${edge.target}\` (${edge.type})`);
      }
    }
    sections.push('');
  }

  // Allowed Dependencies (from layers)
  if (hasLayers && patterns.layers) {
    const hasForbidden = patterns.layers.some(l => l.allowedDependencies.length > 0);
    if (hasForbidden) {
      sections.push('## Dependency Rules\n');
      for (const layer of patterns.layers) {
        if (layer.allowedDependencies.length > 0) {
          sections.push(`- **${layer.name}** may depend on: ${layer.allowedDependencies.join(', ')}`);
        }
      }
      sections.push('');
    }
  }

  if (sections.length === 0) {
    return null;
  }

  const content = [
    GENERATION_HEADER,
    '',
    `---`,
    `inclusion: ${determineInclusionMode(confidence)}`,
    `---`,
    '',
    '# Architecture',
    '',
    ...sections,
  ].join('\n');

  return { content, confidence };
}

/**
 * SteeringFileGenerator produces `.kiro/steering/` files from analysis results.
 * It generates up to three files: coding-standards.md, build-and-test.md, architecture.md.
 */
export class SteeringFileGenerator implements ArtifactGenerator<AnalyzeCodebaseOutput, GeneratedFile[]> {
  readonly name = 'SteeringFileGenerator';

  canGenerate(analysis: AnalyzeCodebaseOutput): boolean {
    // Can generate if we have build pipeline data, architecture patterns, or team conventions
    const hasBuildData = !analysis.buildPipeline.noBuildToolFound || analysis.buildPipeline.scripts.length > 0;
    const hasPatterns = analysis.patterns.patterns.length > 0 ||
      (analysis.patterns.layers !== undefined && analysis.patterns.layers.length > 0) ||
      analysis.patterns.dependencyGraph.length > 0;

    return hasBuildData || hasPatterns;
  }

  async generate(input: AnalyzeCodebaseOutput, config: GenerationConfig): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];

    // Only generate steering files if the artifact type is enabled
    if (!config.artifactTypes.includes('steering')) {
      return files;
    }

    // Coding Standards
    if (
      config.steeringCategories.length === 0 ||
      config.steeringCategories.some(c => ['naming-conventions', 'formatting', 'import-order'].includes(c))
    ) {
      const codingStandards = generateCodingStandards(config.teamConventions, input);
      if (codingStandards) {
        files.push({
          path: '.kiro/steering/coding-standards.md',
          type: 'steering',
          content: codingStandards.content,
          inclusionMode: determineInclusionMode(codingStandards.confidence),
        });
      }
    }

    // Build and Test
    if (
      config.steeringCategories.length === 0 ||
      config.steeringCategories.some(c => ['build-commands', 'test-commands'].includes(c))
    ) {
      const buildAndTest = generateBuildAndTest(input.buildPipeline);
      if (buildAndTest) {
        files.push({
          path: '.kiro/steering/build-and-test.md',
          type: 'steering',
          content: buildAndTest.content,
          inclusionMode: determineInclusionMode(buildAndTest.confidence),
        });
      }
    }

    // Architecture
    if (
      config.steeringCategories.length === 0 ||
      config.steeringCategories.includes('architecture')
    ) {
      const architecture = generateArchitecture(input.patterns);
      if (architecture) {
        files.push({
          path: '.kiro/steering/architecture.md',
          type: 'steering',
          content: architecture.content,
          inclusionMode: determineInclusionMode(architecture.confidence),
        });
      }
    }

    return files;
  }
}
